// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Which screen the binary was launched into, asked once before anything is
	 *  rendered.
	 * 
	 *  A Session carries its request's own description, which is all the loading
	 *  screen can say before the load reaches the pull request itself.
	 */
	describeLaunch: () => __TAURI_INVOKE<LaunchDto>("describe_launch"),
	/**
	 *  Re-reads the settings file and resolves every clone it lists.
	 * 
	 *  Runs when Home opens, after an Add or a Remove, and on `r`. A settings file
	 *  that cannot be read comes back as the snapshot's failure rather than as a
	 *  command error, because the header and footer stay on screen either way.
	 */
	refreshHome: () => __TAURI_INVOKE<HomeSnapshotDto>("refresh_home"),
	/**
	 *  Adds the folders the reviewer picked, writing the file once and refreshing.
	 * 
	 *  A folder that is not a clone of a GitHub repository is refused with its
	 *  reason while the rest proceed, and one already listed is ignored.
	 */
	addRepositories: (folders: string[]) => __TAURI_INVOKE<HomeSnapshotDto>("add_repositories", { folders }),
	/**  Drops one configured clone, writing the file and refreshing. */
	removeRepository: (path: string) => __TAURI_INVOKE<HomeSnapshotDto>("remove_repository", { path }),
	/**  Opens or closes the Repositories footer. */
	toggleRepositoriesFooter: () => __TAURI_INVOKE<HomeSnapshotDto>("toggle_repositories_footer"),
	/**  Clears the refusals the last Add reported. */
	dismissRefusals: () => __TAURI_INVOKE<HomeSnapshotDto>("dismiss_refusals"),
	/**
	 *  Loads the review session the window was opened with, reporting each stage on
	 *  `on_stage` as it goes.
	 * 
	 *  # Errors
	 * 
	 *  Returns the failure the loader reported, projected for the frontend.
	 */
	openSession: (onStage: Channel<string>) => typedError<SessionSnapshotDto, SessionFailureDto>(__TAURI_INVOKE("open_session", { onStage })),
	/**
	 *  Switches the displayed file and returns its rows.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the index is out of range or the session is not ready.
	 */
	selectFile: (index: number) => typedError<FileDetailDto, SessionFailureDto>(__TAURI_INVOKE("select_file", { index })),
	/**
	 *  Marks the selected file viewed, or unmarks it, and returns the fresh sidebar.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready.
	 */
	toggleViewed: () => typedError<SidebarDto, SessionFailureDto>(__TAURI_INVOKE("toggle_viewed")),
	/**
	 *  Edits the draft over rows `start..=end` of `file_index`. Persists the new
	 *  text on every call. That is what makes a keystroke survive a crash.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready. An unanchorable span is not
	 *  an error. It comes back as `accepted: false` on the outcome, and neither is a
	 *  `file_index` that has since been navigated away from; the outcome reflects
	 *  the file that is actually selected.
	 */
	editDraft: (fileIndex: number, start: number, end: number, body: string) => typedError<DraftEditOutcomeDto, SessionFailureDto>(__TAURI_INVOKE("edit_draft", { fileIndex, start, end, body })),
	/**
	 *  Discards the draft on `row` of `file_index`.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready.
	 */
	discardDraft: (fileIndex: number, row: number) => typedError<DraftsDto, SessionFailureDto>(__TAURI_INVOKE("discard_draft", { fileIndex, row })),
	/**
	 *  Moves a stale draft, named by the position it was written against, onto
	 *  `row` of `file_index`.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready, no stale draft matches
	 *  `(path, side, line)`, or `row` cannot carry a comment.
	 */
	reanchorDraft: (fileIndex: number, path: string, side: DiffSideDto, line: number, row: number) => typedError<DraftsDto, SessionFailureDto>(__TAURI_INVOKE("reanchor_draft", { fileIndex, path, side, line, row })),
};

/* Types */
/**  A picked folder Home would not add, and why. */
export type AddRefusalDto = {
	folder: string,
	reason: string,
};

/**  A draft resolved to the row it is drawn on. */
export type AnchoredDraftDto = {
	row: number,
	body: string,
	is_proposed: boolean,
};

export type DiffLineKindDto = "Context" | "Addition" | "Deletion" | "NoNewlineMarker";

export type DiffSideDto = "Left" | "Right";

/**  The outcome of an edit, discard, or reanchor on the composer. */
export type DraftEditOutcomeDto = {
	accepted: boolean,
	drafts: DraftsDto,
};

/**
 *  Every draft that belongs to one file, projected for a per-keystroke response.
 * 
 *  Deliberately narrow. Refetching a whole [`FileDetailDto`] on every keystroke
 *  would re-send up to 100,000 rows for a single character typed.
 */
export type DraftsDto = {
	file_index: number,
	anchored: AnchoredDraftDto[],
	stale: StaleDraftDto[],
	file_draft_count: number,
	write_failure: string | null,
};

/**  Why a file shows no diff rows. */
export type EmptyReasonDto = {
	label: string,
	detail: string,
};

export type FileDetailDto = {
	index: number,
	path: string,
	rows: RowDto[],
	drafts: DraftsDto,
	empty_reason: EmptyReasonDto | null,
};

export type FileStatusDto = "Added" | "Deleted" | "Modified" | "Renamed" | "Copied" | "TypeChanged" | "Unmerged";

export type FileSummaryDto = {
	index: number,
	path: string,
	old_path: string | null,
	status: FileStatusDto,
	is_binary: boolean,
	additions: number,
	deletions: number,
	viewed: boolean,
	thread_count: number,
};

/**  One of Home's three groups, always rendered whether or not it has rows. */
export type HomeGroupDto = {
	title: string,
	count: number,
	/**  The one line an empty group shows in place of rows. */
	empty_copy: string,
};

/**  One configured clone as the footer lists it. */
export type HomeRepositoryDto = {
	path: string,
	slug: string | null,
	/**  Why this clone cannot be listed, absent when it resolved. */
	failure: string | null,
};

/**  Everything Home renders, from its header to its footer. */
export type HomeSnapshotDto = {
	/**  The header's count line, absent until there is something to count. */
	count_line: string | null,
	groups: HomeGroupDto[],
	repositories: HomeRepositoryDto[],
	footer_summary: string,
	footer_expanded: boolean,
	refusals: AddRefusalDto[],
	/**
	 *  What replaces the list area when Home cannot read its repositories. The
	 *  header and footer stay either way, so Add still works.
	 */
	failure: SessionFailureDto | null,
};

/**  Which screen the binary was launched into. */
export type LaunchDto = "Home" | { Session: {
	description: string,
} };

export type RowDto = {
	kind: DiffLineKindDto,
	old_line: number | null,
	new_line: number | null,
	text: string,
	/**
	 *  The header of the hunk that starts at this row, if one does.
	 * 
	 *  Rides above the row rather than occupying one of its own, so a row index
	 *  always equals its line index.
	 */
	hunk_header: string | null,
	thread_count: number,
};

export type SessionFailureDto = {
	summary: string,
	detail: string | null,
	remediation: string | null,
};

export type SessionSnapshotDto = {
	title: string,
	subtitle: string,
	sidebar: SidebarDto,
	warnings: SessionFailureDto[],
};

export type SidebarDto = {
	files: FileSummaryDto[],
	selected_file: number,
	viewed_count: number,
	thread_count: number,
};

/**  A draft whose anchor no longer resolves against the current diff. */
export type StaleDraftDto = {
	path: string,
	side: DiffSideDto,
	line: number,
	body: string,
	/**  Where the draft used to sit, formatted for display, e.g. "was RIGHT line 42". */
	location: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

