// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Which screen the window shows, and the Session it is holding.
	 * 
	 *  Asked once before anything is rendered, and again after every navigation. A
	 *  Session carries its request's own description, which is all the loading
	 *  screen can say before the load reaches the pull request itself.
	 */
	describeWindow: () => __TAURI_INVOKE<WindowDto>("describe_window"),
	/**
	 *  Re-reads the settings file, then fetches what every clone it lists has open.
	 * 
	 *  Runs when Home opens, on `r`, and after an Add or a Remove. Everything Home
	 *  shows goes to `on_progress` as each batch of repositories lands, so the list
	 *  fills in as it loads. A trigger that arrives mid-refresh starts nothing and
	 *  answers with what is already on screen.
	 * 
	 *  A settings file that cannot be read, or a `gh` that cannot be used, comes
	 *  back inside the snapshot rather than as a command error, because the header
	 *  and footer stay on screen either way.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the task doing the fetching does not finish.
	 */
	refreshHome: (onProgress: Channel<HomeSnapshotDto>) => typedError<HomeSnapshotDto, SessionFailureDto>(__TAURI_INVOKE("refresh_home", { onProgress })),
	/**  Moves the cursor one row through the list, across the groups. */
	moveHomeCursor: (moveTo: CursorMoveDto) => __TAURI_INVOKE<HomeSnapshotDto>("move_home_cursor", { moveTo }),
	/**
	 *  Adds the folders the reviewer picked, writing the file once and reading it
	 *  back.
	 * 
	 *  A folder that is not a clone of a GitHub repository is refused with its
	 *  reason while the rest proceed, and one already listed is ignored. The pull
	 *  requests of a repository just added arrive with the refresh the caller runs
	 *  next, not with this.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the task doing the work does not finish.
	 */
	addRepositories: (folders: string[]) => typedError<HomeSnapshotDto, SessionFailureDto>(__TAURI_INVOKE("add_repositories", { folders })),
	/**
	 *  Drops one configured clone, writing the file and reading it back.
	 * 
	 *  The list is left as it stands otherwise. It is the refresh the caller runs
	 *  next that asks GitHub about what remains.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the task doing the work does not finish.
	 */
	removeRepository: (path: string) => typedError<HomeSnapshotDto, SessionFailureDto>(__TAURI_INVOKE("remove_repository", { path })),
	/**  Opens or closes the Repositories footer. */
	toggleRepositoriesFooter: () => __TAURI_INVOKE<HomeSnapshotDto>("toggle_repositories_footer"),
	/**
	 *  Opens the pull request a Home row names, replacing whatever Session was
	 *  alive.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no configured clone resolves to `repository`, which
	 *  leaves the Session that was alive exactly as it was.
	 */
	openRow: (repository: string, number: number) => typedError<OpenRowOutcomeDto, SessionFailureDto>(__TAURI_INVOKE("open_row", { repository, number })),
	/**
	 *  Opens the pull request a Home row names, first cancelling the run the
	 *  Session alive was running.
	 * 
	 *  Reached only once the reviewer has answered the confirmation `open_row`
	 *  asked for by answering [`dto::OpenRowOutcomeDto::Blocked`].
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no configured clone resolves to `repository`, which
	 *  leaves the Session that was alive exactly as it was.
	 */
	openRowCancellingRun: (repository: string, number: number) => typedError<WindowDto, SessionFailureDto>(__TAURI_INVOKE("open_row_cancelling_run", { repository, number })),
	/**
	 *  Shows Home again, leaving the Session alive behind it.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure for a Session the command line opened, which has no Home
	 *  behind it to go back to.
	 */
	returnToHome: () => typedError<WindowDto, SessionFailureDto>(__TAURI_INVOKE("return_to_home")),
	/**
	 *  Shows the Session alive behind Home again, exactly as it was left.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no Session is alive, which the header slot's own
	 *  absence already keeps a reviewer from asking for.
	 */
	returnToSession: () => typedError<WindowDto, SessionFailureDto>(__TAURI_INVOKE("return_to_session")),
	/**
	 *  Loads the review session the window was opened with, reporting each stage on
	 *  `on_stage` as it goes.
	 * 
	 *  # Errors
	 * 
	 *  Returns the failure the loader reported, projected for the frontend.
	 */
	openSession: (onStage: Channel<string>) => typedError<SessionSnapshotDto, SessionFailureDto>(__TAURI_INVOKE("open_session", { onStage })),
	/**
	 *  Switches the displayed file and returns its rows.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the index is out of range or the session is not ready.
	 */
	selectFile: (index: number) => typedError<FileDetailDto, SessionFailureDto>(__TAURI_INVOKE("select_file", { index })),
	/**
	 *  Marks the selected file viewed, or unmarks it, and returns the fresh sidebar.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready.
	 */
	toggleViewed: () => typedError<SidebarDto, SessionFailureDto>(__TAURI_INVOKE("toggle_viewed")),
	/**
	 *  Edits the draft over rows `start..=end` of `file_index`. Persists the new
	 *  text on every call. That is what makes a keystroke survive a crash.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready. An unanchorable span is not
	 *  an error. It comes back as `accepted: false` on the outcome, and neither is a
	 *  `file_index` that has since been navigated away from; the outcome reflects
	 *  the file that is actually selected.
	 */
	editDraft: (fileIndex: number, start: number, end: number, body: string) => typedError<DraftEditOutcomeDto, SessionFailureDto>(__TAURI_INVOKE("edit_draft", { fileIndex, start, end, body })),
	/**
	 *  Discards the draft on `row` of `file_index`.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready.
	 */
	discardDraft: (fileIndex: number, row: number) => typedError<DraftsDto, SessionFailureDto>(__TAURI_INVOKE("discard_draft", { fileIndex, row })),
	/**
	 *  Moves a stale draft, named by the position it was written against, onto
	 *  `row` of `file_index`.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when the session is not ready, no stale draft matches
	 *  `(path, side, line)`, or `row` cannot carry a comment.
	 */
	reanchorDraft: (fileIndex: number, path: string, side: DiffSideDto, line: number, row: number) => typedError<DraftsDto, SessionFailureDto>(__TAURI_INVOKE("reanchor_draft", { fileIndex, path, side, line, row })),
	/**
	 *  The Session's review panel, asked for once the session is ready.
	 * 
	 *  `null` means this snapshot cannot be reviewed at all, which is the generated
	 *  fixture, and the Session shows no panel.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	reviewPanel: () => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("review_panel")),
	/**
	 *  Runs a review against the Claude coding agent at the repository root, on a
	 *  background thread, reporting the panel to `on_progress` as the backend speaks.
	 * 
	 *  A trigger that arrives while a run is in flight starts nothing and answers with
	 *  the panel already on screen. The model is taken out of the window as its own
	 *  handle, so a Session dropped or a window closed mid-run leaves the background
	 *  work finishing into a model nobody reads rather than panicking.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, or when the task doing the review
	 *  does not finish.
	 */
	runReview: (onProgress: Channel<ReviewPanelDto>) => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("run_review", { onProgress })),
	/**
	 *  Asks the running review to stop. It ends at the backend's next step.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	cancelReview: () => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("cancel_review")),
	/**
	 *  Opens or closes the guidance section.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	toggleGuidancePanel: () => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("toggle_guidance_panel")),
	/**
	 *  Turns one guidance file on or off for the next run.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, or when `path` names no guidance
	 *  file the session discovered.
	 */
	toggleGuidance: (path: string) => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("toggle_guidance", { path })),
	/**
	 *  Accepts a finding, turning it into a draft where the model allows it.
	 * 
	 *  Refuses to overwrite the reviewer's own draft. The disposition answers
	 *  `Occupied` instead, and the panel asks whether to replace it.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	acceptFinding: (id: number) => typedError<{
	panel: ReviewPanelDto,
	/**  The selected file's drafts, refreshed in case the finding landed there. */
	drafts: DraftsDto,
	disposition: AcceptDispositionDto,
} | null, SessionFailureDto>(__TAURI_INVOKE("accept_finding", { id })),
	/**
	 *  Forces a finding onto its anchor, overwriting the reviewer's own draft there.
	 * 
	 *  Reached only once the reviewer has chosen to replace what they wrote, after
	 *  `accept_finding` answered with the confirmation.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	overwriteFinding: (id: number) => typedError<{
	panel: ReviewPanelDto,
	/**  The selected file's drafts, refreshed in case the finding landed there. */
	drafts: DraftsDto,
	disposition: AcceptDispositionDto,
} | null, SessionFailureDto>(__TAURI_INVOKE("overwrite_finding", { id })),
	/**
	 *  Dismisses a finding, recording the decision so a later run suppresses the
	 *  same claim.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	dismissFinding: (id: number) => typedError<{
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("dismiss_finding", { id })),
	/**
	 *  Selects a finding, scrolling the diff to its anchor and selecting the row.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	revealFinding: (id: number) => typedError<{
	panel: ReviewPanelDto,
	/**
	 *  Absent for a finding about the change as a whole, which has nowhere to
	 *  scroll to.
	 */
	location: FindingLocationDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("reveal_finding", { id })),
	/**
	 *  Moves the selection to the finding after the one selected, wrapping to the
	 *  first, and scrolls the diff to show it.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open.
	 */
	selectNextFinding: () => typedError<{
	panel: ReviewPanelDto,
	/**
	 *  Absent for a finding about the change as a whole, which has nowhere to
	 *  scroll to.
	 */
	location: FindingLocationDto | null,
} | null, SessionFailureDto>(__TAURI_INVOKE("select_next_finding")),
	/**
	 *  Stores the review summary, keyed by pull request and head.
	 * 
	 *  Called on every keystroke, like a draft edit. That is what makes the text
	 *  survive a crash, and what a later Session restores it from. Answers with
	 *  what is stopping writes landing, if anything is, which for a reviewer
	 *  writing only a summary is the one place that can say so.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, or the session is not ready.
	 */
	editSummary: (body: string) => typedError<string | null, SessionFailureDto>(__TAURI_INVOKE("edit_summary", { body })),
	/**
	 *  Assembles what submitting would post and holds it for approval.
	 * 
	 *  Posts nothing. What comes back is the exact request that would be sent, so
	 *  what the reviewer approves is what leaves the machine.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, or the session is not ready.
	 */
	requestSubmission: (event: ReviewEventDto) => typedError<SubmissionDto, SessionFailureDto>(__TAURI_INVOKE("request_submission", { event })),
	/**
	 *  Puts the confirmation away, leaving every draft and the summary as they were.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, or the session is not ready.
	 */
	cancelSubmission: () => typedError<SubmissionDto, SessionFailureDto>(__TAURI_INVOKE("cancel_submission")),
	/**
	 *  Posts the confirmed review on a background thread, then reports what the
	 *  forge said.
	 * 
	 *  The sending state goes to `on_sending` before the post starts, so the panel
	 *  stops offering a confirmation the moment one is acted on. The model is taken
	 *  out of the window as its own handle, so a Session dropped or a window closed
	 *  mid-send leaves the post finishing into a model nobody reads rather than
	 *  panicking. A second call while the first is in flight posts nothing more, and
	 *  a task that dies without reporting leaves a submission that can be retried.
	 * 
	 *  # Errors
	 * 
	 *  Returns a failure when no session is open, the session is not ready, or the
	 *  task doing the posting does not finish.
	 */
	sendSubmission: (onSending: Channel<SubmissionDto>) => typedError<SendOutcomeDto, SessionFailureDto>(__TAURI_INVOKE("send_submission", { onSending })),
};

/* Types */
/**  What accepting a finding left for the panel to do. */
export type AcceptDispositionDto = 
/**  Became a draft at the anchor, which the diff now shows the mark for. */
{ outcome: "Drafted" } | 
/**
 *  The anchor already held the reviewer's own draft. Neither text was
 *  written; the panel asks whether to replace it. `location` is where
 *  accepting it should first reveal, as the GPUI composer path does.
 */
{ outcome: "Occupied"; existing: string; proposed: string; location: FindingLocationDto } | 
/**
 *  The finding was about the change as a whole, so its proposal went into the
 *  summary. `body` is what the editor should now hold, the reviewer's own
 *  text and the proposal together.
 */
{ outcome: "Summary"; body: string } | 
/**  No pending finding had that id. */
{ outcome: "Unknown" };

/**  What accepting or replacing a finding answers with. */
export type AcceptOutcomeDto = {
	panel: ReviewPanelDto,
	/**  The selected file's drafts, refreshed in case the finding landed there. */
	drafts: DraftsDto,
	disposition: AcceptDispositionDto,
};

/**  A draft resolved to the row it is drawn on. */
export type AnchoredDraftDto = {
	row: number,
	body: string,
	is_proposed: boolean,
};

/**  Which way the cursor is being moved. */
export type CursorMoveDto = "Down" | "Up";

export type DiffLineKindDto = "Context" | "Addition" | "Deletion" | "NoNewlineMarker";

export type DiffSideDto = "Left" | "Right";

/**  The outcome of an edit, discard, or reanchor on the composer. */
export type DraftEditOutcomeDto = {
	accepted: boolean,
	drafts: DraftsDto,
};

/**
 *  Every draft that belongs to one file, projected for a per-keystroke response.
 * 
 *  Deliberately narrow. Refetching a whole [`FileDetailDto`] on every keystroke
 *  would re-send up to 100,000 rows for a single character typed.
 */
export type DraftsDto = {
	file_index: number,
	anchored: AnchoredDraftDto[],
	stale: StaleDraftDto[],
	file_draft_count: number,
	/**
	 *  Every draft in the session that would be posted, not just this file's,
	 *  which is the count the submit bar leads with.
	 */
	ready_count: number,
	/**
	 *  Every draft in the session whose anchor no longer resolves. Counted apart
	 *  because a submission leaves these behind.
	 */
	not_anchored_count: number,
	write_failure: string | null,
};

/**  Why a file shows no diff rows. */
export type EmptyReasonDto = {
	label: string,
	detail: string,
};

/**  A draft the submission leaves behind, and why. */
export type ExcludedDraftDto = {
	/**  "path line N", where the draft still claims to be. */
	position: string,
	/**  Why it will not be posted, e.g. "not on a line in the current diff". */
	reason: string,
	body: string,
};

/**  One configured repository whose pull requests could not be fetched. */
export type FailedRepositoryDto = {
	/**  The entry in the settings file, which is what Remove names. */
	path: string,
	slug: string,
	reason: string,
};

export type FileDetailDto = {
	index: number,
	path: string,
	rows: RowDto[],
	drafts: DraftsDto,
	empty_reason: EmptyReasonDto | null,
};

export type FileStatusDto = "Added" | "Deleted" | "Modified" | "Renamed" | "Copied" | "TypeChanged" | "Unmerged";

export type FileSummaryDto = {
	index: number,
	path: string,
	old_path: string | null,
	status: FileStatusDto,
	is_binary: boolean,
	additions: number,
	deletions: number,
	viewed: boolean,
	thread_count: number,
};

/**  A suggestion a review backend proposed, waiting for the reviewer to act on it. */
export type FindingDto = {
	id: number,
	severity: SeverityDto,
	/**
	 *  Rounded to a whole percentage; a fraction reads as odd precision to a
	 *  reviewer deciding whether to spend attention on it.
	 */
	confidence_percent: number,
	title: string,
	rationale: string,
	/**  Guidance paths this finding cites, e.g. "AGENTS.md". */
	citations: string[],
	/**  The backend that proposed this, e.g. "claude-code". */
	origin: string,
	/**  "path:line", absent for a finding about the change as a whole. */
	position: string | null,
	is_selected: boolean,
};

/**  Where a finding's anchor lands in the displayed diff. */
export type FindingLocationDto = {
	file: number,
	row: number,
};

/**  The guidance section at the top of the panel. */
export type GuidanceDto = 
/**
 *  Discovery ran and found nothing. Saying so is not the same as showing
 *  nothing. A reviewer needs to tell "this repository states no conventions"
 *  from "guidance was never looked for".
 */
{ kind: "NothingFound"; note: string } | { kind: "Discovered"; 
/**  The one line that stays on screen whether or not the section is open. */
summary: string; expanded: boolean; entries: GuidanceEntryDto[]; skipped: GuidanceSkipDto[]; 
/**  What configuration keeps out of the review, when it keeps anything out. */
excluded: string | null };

/**  One guidance file discovery found, as the panel draws its row. */
export type GuidanceEntryDto = {
	/**  Repository-relative path, which is also how a finding cites it. */
	path: string,
	/**  What it applies to, already rendered, e.g. "whole repository". */
	scope: string,
	kilobytes: number,
	/**  Whether the next run will send it. */
	included: boolean,
};

/**  Something discovery found and will not use, and why. */
export type GuidanceSkipDto = {
	path: string,
	reason: string,
};

/**  One of Home's three groups, always rendered whether or not it has rows. */
export type HomeGroupDto = {
	title: string,
	count: number,
	/**  The one line an empty group shows in place of rows. */
	empty_copy: string,
	rows: HomeRowDto[],
};

/**  One configured clone as the footer lists it. */
export type HomeRepositoryDto = {
	path: string,
	slug: string | null,
	/**  Why this clone cannot be listed, absent when it resolved. */
	failure: string | null,
};

/**  One pull request, as one line of the ledger. */
export type HomeRowDto = {
	/**  Where this row sits in the flat order the cursor walks. */
	index: number,
	title: string,
	url: string,
	/**  `owner/name`, which opening this row names its pull request by. */
	repository: string,
	number: number,
	/**  `owner/name#number`. */
	identity: string,
	/**  Absent once GitHub has forgotten the account. */
	author: string | null,
	/**
	 *  When the pull request last moved, as epoch milliseconds, which the age
	 *  column is worked out from.
	 */
	updated_at_ms: number,
	review_status: RowStatusDto | null,
	check_status: RowStatusDto | null,
	/**  "1 draft" or "N drafts", absent for a blank cell. */
	drafts_label: string | null,
	/**
	 *  Whether the Session alive behind Home is open on this row's pull
	 *  request, which is what the row's accent mark says.
	 */
	is_alive: boolean,
};

/**  Everything Home renders, from its header to its footer. */
export type HomeSnapshotDto = {
	/**  The header's count line, absent until there is something to count. */
	count_line: string | null,
	groups: HomeGroupDto[],
	/**  Where the cursor sits, as a flat index across every rendered row. */
	cursor: number,
	refresh: RefreshStateDto,
	/**  One line each above the list, naming a repository this refresh lost. */
	failed_repositories: FailedRepositoryDto[],
	repositories: HomeRepositoryDto[],
	footer_summary: string,
	footer_expanded: boolean,
	refusals: RefusalDto[],
	/**
	 *  What replaces the list area when Home cannot read its repositories or
	 *  cannot use `gh`. The header and footer stay either way, so Add still
	 *  works.
	 */
	failure: SessionFailureDto | null,
	/**
	 *  Why the last write did not reach the file, shown as a line above the
	 *  list, which stays because reading it still worked.
	 */
	write_failure: SessionFailureDto | null,
	/**
	 *  Why the last Drafts read failed, shown as a line above the list beside
	 *  the failed repositories, with every row's Drafts column left blank.
	 */
	drafts_failure: SessionFailureDto | null,
};

/**  What opening a row answered with. */
export type OpenRowOutcomeDto = 
/**  The row opened, or the Session already alive on it was shown again. */
{ outcome: "Opened"; window: WindowDto } | 
/**
 *  The Session alive behind Home has a live run in the way. Nothing was
 *  touched; the frontend asks the reviewer to cancel the run and continue,
 *  or stay.
 */
{ outcome: "Blocked" };

/**  The one Session the window holds, in front of Home or alive behind it. */
export type OpenSessionDto = {
	/**
	 *  What is being opened, which is all the loading screen can say before the
	 *  load reaches the pull request itself.
	 */
	description: string,
	/**
	 *  `owner/name#number` of the row this Session was opened from, which the
	 *  header slot reads and Home marks that row by. Absent for a Session the
	 *  command line opened, and its absence is what says there is no Home to go
	 *  back to.
	 */
	row_identity: string | null,
};

/**  The caveats under the panel: what was refused, and what was never looked at. */
export type PanelFooterDto = {
	/**  Claims that did not survive checking against the diff. */
	refused: string | null,
	/**  Present when a completed run did not see the whole change. */
	not_reviewed: string | null,
	/**  The files that run did not see, named under the count that describes them. */
	unreviewed: string[],
};

/**
 *  What the panel says when there is no finding to show.
 * 
 *  Every run state has one. An empty panel with no explanation is the failure
 *  this projection exists to avoid.
 */
export type PanelNoteDto = {
	heading: string,
	detail: string | null,
};

/**  How current the list is, which the header stamp reads. */
export type RefreshStateDto = 
/**  There is no stamp at all until the first refresh starts. */
"NeverRefreshed" | ({ Refreshing: {
	done: number,
	total: number,
} }) & { Refreshed?: never } | 
/**  Epoch milliseconds, which the relative stamp is worked out from. */
({ Refreshed: {
	at_ms: number,
} }) & { Refreshing?: never } | "Failed";

/**  Something Home would not do, and why. */
export type RefusalDto = {
	path: string,
	reason: string,
};

/**  What revealing a finding, or selecting the next one, answers with. */
export type RevealOutcomeDto = {
	panel: ReviewPanelDto,
	/**
	 *  Absent for a finding about the change as a whole, which has nowhere to
	 *  scroll to.
	 */
	location: FindingLocationDto | null,
};

/**  What submitting the review asserts about it. */
export type ReviewEventDto = "Comment" | "Approve" | "RequestChanges";

/**
 *  The Session's right-hand panel: what a review is held to, and how far the run
 *  that populates it has got.
 */
export type ReviewPanelDto = {
	/**
	 *  How many times the panel has changed, so a snapshot that was read before
	 *  a change can be told from one that carries it.
	 */
	revision: number,
	/**  "Review" before there is anything to act on, otherwise the finding count. */
	heading: string,
	guidance: GuidanceDto,
	run: ReviewRunDto,
	note: PanelNoteDto | null,
	/**  Waiting for the reviewer, most severe and most confident first. */
	findings: FindingDto[],
	footer: PanelFooterDto | null,
};

/**  How far the current review run has got. */
export type ReviewRunDto = { state: "Idle" } | { state: "Running"; 
/**  The backend's most recent progress line. */
detail: string } | { state: "Complete"; accepted: number; rejected: number; 
/**  Claims suppressed because the reviewer dismissed them before. */
suppressed: number } | { state: "Failed"; summary: string; remediation: string | null };

export type RowDto = {
	kind: DiffLineKindDto,
	old_line: number | null,
	new_line: number | null,
	text: string,
	/**
	 *  The header of the hunk that starts at this row, if one does.
	 * 
	 *  Rides above the row rather than occupying one of its own, so a row index
	 *  always equals its line index.
	 */
	hunk_header: string | null,
	thread_count: number,
};

/**  One status column's words and the weight they carry. */
export type RowStatusDto = {
	label: string,
	tone: StatusToneDto,
};

/**  What a send answers with once the forge has replied. */
export type SendOutcomeDto = {
	submission: SubmissionDto,
	/**  The selected file's drafts, emptied of whatever was posted. */
	drafts: DraftsDto,
	/**  What the summary editor should now hold, which a successful send empties. */
	summary: string,
};

export type SessionFailureDto = {
	summary: string,
	detail: string | null,
	remediation: string | null,
};

export type SessionSnapshotDto = {
	title: string,
	subtitle: string,
	sidebar: SidebarDto,
	warnings: SessionFailureDto[],
	/**
	 *  Whether this Session has somewhere to post a review, which is what decides
	 *  if the submit bar is there at all. False for the generated fixture and a
	 *  local comparison, neither of which is a pull request.
	 */
	can_submit: boolean,
	/**
	 *  What the summary editor seeds from, restored from storage on a fresh load
	 *  of the same pull request and head.
	 */
	summary: string,
};

/**  How much a finding claims to matter. */
export type SeverityDto = "Info" | "Warning" | "Error";

export type SidebarDto = {
	files: FileSummaryDto[],
	selected_file: number,
	viewed_count: number,
	thread_count: number,
};

/**  A draft whose anchor no longer resolves against the current diff. */
export type StaleDraftDto = {
	path: string,
	side: DiffSideDto,
	line: number,
	body: string,
	/**  Where the draft used to sit, formatted for display, e.g. "was RIGHT line 42". */
	location: string,
};

/**
 *  Which severity a status column paints itself in.
 * 
 *  Named rather than coloured, so the values themselves stay in the one style
 *  sheet that owns them.
 */
export type StatusToneDto = "Success" | "Error" | "Warning" | "Muted";

/**  The submission, and how many times it has changed. */
export type SubmissionDto = {
	/**
	 *  So a snapshot read before a change can be told from one that carries it.
	 *  Several submission commands can be in flight at once.
	 */
	revision: number,
	phase: SubmissionPhaseDto,
};

/**  A review the forge accepted. */
export type SubmissionOutcomeDto = {
	/**
	 *  What it was recorded as and how much went with it, e.g. "Submitted as
	 *  COMMENTED with 1 inline comment".
	 */
	heading: string,
	/**  Where to read it. */
	url: string,
};

/**  How far the submission has got. */
export type SubmissionPhaseDto = { state: "Idle" } | 
/**  Holding the exact request, waiting on a person. Nothing has been posted. */
{ state: "Confirming"; request: SubmissionRequestDto } | { state: "Sending" } | { state: "Sent"; outcome: SubmissionOutcomeDto } | 
/**
 *  The forge refused it, or it could not be assembled at all. Every draft
 *  and the summary are still exactly where they were.
 */
{ state: "Failed"; failure: SessionFailureDto };

/**
 *  The exact request a confirmed submission would post.
 * 
 *  Mirrors the GPUI confirmation in `crates/ui`: what the reviewer approves is
 *  what leaves the machine, so every part of it is shown rather than summarised.
 */
export type SubmissionRequestDto = {
	/**
	 *  The verdict and how many inline comments go with it, e.g. "Comment with
	 *  1 inline comment".
	 */
	heading: string,
	/**
	 *  "pinned to abc1234". Shown because it is what the forge can still reject
	 *  the review for.
	 */
	pinned: string,
	body: string,
	comments: SubmittableCommentDto[],
	/**  Always shown. A reviewer must not believe these were posted. */
	excluded: ExcludedDraftDto[],
	/**  "1 draft will NOT be posted", absent when nothing is excluded. */
	excluded_heading: string | null,
};

/**  One inline comment, at the position the forge will be given for it. */
export type SubmittableCommentDto = {
	/**  "path SIDE line N", which is the position itself, not a paraphrase of it. */
	position: string,
	body: string,
};

/**  Which screen the window shows, and the Session it is holding. */
export type WindowDto = 
/**
 *  Home, with the Session alive behind it when there is one. That Session's
 *  tree stays mounted and hidden, which is what makes returning instant.
 */
({ Home: {
	alive: OpenSessionDto | null,
} }) & { Session?: never } | 
/**  The Session, in front of Home or with no Home behind it at all. */
({ Session: {
	session: OpenSessionDto,
} }) & { Home?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

